PROTOWORKS_VERSION = "0.1"
PROTOWORKS_FILETYPES_VERSION = "0.1"

PROJECT_IN_WORK = 0
PROJECT_DONE = 1

ACTION_SYNC_ALL_NEW_FILES = 0
ACTION_OVERRIDE_SERVER_FILES = 1
ACTION_OVERRIDE_CLIENT_FILES = 2
ACTION_SEND_ONLY_NEW_FILES_FROM_SERVER = 3
ACTION_SEND_ONLY_NEW_FILES_FROM_CLIENT = 4
ACTION_SEND_ONLY_EDITED_FILES_FROM_SERVER = 5
ACTION_SEND_ONLY_EDITED_FILES_FROM_CLIENT = 6

ACTION_TRANSLATIONS = {
    ACTION_SYNC_ALL_NEW_FILES: "Синхронизация",
    ACTION_OVERRIDE_SERVER_FILES: "Перезапись серверной директории",
    ACTION_OVERRIDE_CLIENT_FILES: "Перезапись локальной директории",
    ACTION_SEND_ONLY_NEW_FILES_FROM_SERVER: "Получение новых файлов с сервера",
    ACTION_SEND_ONLY_NEW_FILES_FROM_CLIENT: "Отправление новых файлов на сервер",
    ACTION_SEND_ONLY_EDITED_FILES_FROM_SERVER: "Получение измененных файлов с сервера",
    ACTION_SEND_ONLY_EDITED_FILES_FROM_CLIENT: "Отправление измененных файлов на сервер"
    }

BIG_FILE_SIZE = 10*1024*1024 # bytes
CHUNK_SIZE = 5120

CUR_CLIENT = 0
SERVER = 1
FILE = 0
FOLDER = 1