PROTOWORKS_VERSION = "0.1"
PROTOWORKS_FILETYPES_VERSION = "0.1"

INVALID_REQUEST_ASNWER = ("Invalid request", 400)
AUTH_ERROR = ("Invalid auth", 302)

PROJECT_IN_WORK = 0
PROJECT_DONE = 1

CLIENT = 0
SERVER = 1
FILE = 0
FOLDER = 1